[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { version = "0.1.0", path = "../common" }
anyhow = "1.0.71"
x11rb = "0.12.0"
notify-rust = "4.8.0"
